package com.microblog.blog.dao.mapper;

import com.microblog.blog.dao.model.BlogCollect;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface BlogCollectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_collect
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long collectId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_collect
     *
     * @mbggenerated
     */
    int insert(BlogCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_collect
     *
     * @mbggenerated
     */
    BlogCollect selectByPrimaryKey(Long collectId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_collect
     *
     * @mbggenerated
     */
    List<BlogCollect> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_collect
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BlogCollect record);

    Long selectCountByBlogId(@Param("blogId") Long blogId);
    Long selectCount(@Param("blogId") Long blogId,@Param("userId") Long userId);
}