package com.microblog.blog.dao.mapper;


import com.microblog.blog.dao.model.BlogComment;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface BlogCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_comment
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_comment
     *
     * @mbggenerated
     */
    int insert(BlogComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_comment
     *
     * @mbggenerated
     */
    BlogComment selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_comment
     *
     * @mbggenerated
     */
    List<BlogComment> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_comment
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BlogComment record);

    List<BlogComment> selectParent(@Param("blogId") long blogId, @Param("page") int page, @Param("pageCount") int pageCount);

    List<BlogComment> selectChild(List<Long> list);
    Integer deleteComment(@Param("commentId") Long commentId);

    Long selectCountByBlogId(Long blogId);
}