package com.microblog.blog.dao.model;

import java.util.Date;

public class BlogLike {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_like.like_id
     *
     * @mbggenerated
     */
    private Long likeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_like.blog_id
     *
     * @mbggenerated
     */
    private Long blogId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_like.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_like.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_like.like_id
     *
     * @return the value of blog_like.like_id
     *
     * @mbggenerated
     */
    public Long getLikeId() {
        return likeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_like.like_id
     *
     * @param likeId the value for blog_like.like_id
     *
     * @mbggenerated
     */
    public void setLikeId(Long likeId) {
        this.likeId = likeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_like.blog_id
     *
     * @return the value of blog_like.blog_id
     *
     * @mbggenerated
     */
    public Long getBlogId() {
        return blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_like.blog_id
     *
     * @param blogId the value for blog_like.blog_id
     *
     * @mbggenerated
     */
    public void setBlogId(Long blogId) {
        this.blogId = blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_like.user_id
     *
     * @return the value of blog_like.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_like.user_id
     *
     * @param userId the value for blog_like.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_like.create_time
     *
     * @return the value of blog_like.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_like.create_time
     *
     * @param createTime the value for blog_like.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}