package com.microblog.points.dao.model;

import com.fasterxml.jackson.annotation.JsonFormat;
import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table quartz_job
 */
public class QuartzJob {
    /**
     * Database Column Remarks:
     *   ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quartz_job.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   任务名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quartz_job.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   任务描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quartz_job.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     * Database Column Remarks:
     *   时间表达式
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quartz_job.cron
     *
     * @mbg.generated
     */
    private String cron;

    /**
     * Database Column Remarks:
     *   任名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quartz_job.job_class
     *
     * @mbg.generated
     */
    private String jobClass;

    /**
     * Database Column Remarks:
     *   任务组别
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quartz_job.job_group
     *
     * @mbg.generated
     */
    private String jobGroup;

    /**
     * Database Column Remarks:
     *   状态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quartz_job.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quartz_job.create_time
     *
     * @mbg.generated
     */
    //@JSONField(format="yyyy-MM-dd HH:mm:ss:SSS")
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone = "GMT+8")
    private Date createTime;

    /**
     * Database Column Remarks:
     *   创建人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quartz_job.create_by
     *
     * @mbg.generated
     */
    private String createBy;

    /**
     * Database Column Remarks:
     *   开始时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quartz_job.start_at
     *
     * @mbg.generated
     */
    //@JSONField(format="yyyy-MM-dd HH:mm:ss:SSS")
    //@DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss:SSS")
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone = "GMT+8")
    private Date startAt;

    /**
     * Database Column Remarks:
     *   结束时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quartz_job.end_at
     *
     * @mbg.generated
     */
    //@DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss:SSS")
    @DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss:SSS")
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone = "GMT+8")
    private Date endAt;

    /**
     * Database Column Remarks:
     *   删除时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quartz_job.delete_time
     *
     * @mbg.generated
     */
    //@JSONField(format="yyyy-MM-dd HH:mm:ss:SSS")
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone = "GMT+8")
    private Date deleteTime;

    /**
     * Database Column Remarks:
     *   删除人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quartz_job.delete_by
     *
     * @mbg.generated
     */
    private String deleteBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quartz_job.id
     *
     * @return the value of quartz_job.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quartz_job.id
     *
     * @param id the value for quartz_job.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quartz_job.name
     *
     * @return the value of quartz_job.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quartz_job.name
     *
     * @param name the value for quartz_job.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quartz_job.description
     *
     * @return the value of quartz_job.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quartz_job.description
     *
     * @param description the value for quartz_job.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quartz_job.cron
     *
     * @return the value of quartz_job.cron
     *
     * @mbg.generated
     */
    public String getCron() {
        return cron;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quartz_job.cron
     *
     * @param cron the value for quartz_job.cron
     *
     * @mbg.generated
     */
    public void setCron(String cron) {
        this.cron = cron;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quartz_job.job_class
     *
     * @return the value of quartz_job.job_class
     *
     * @mbg.generated
     */
    public String getJobClass() {
        return jobClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quartz_job.job_class
     *
     * @param jobClass the value for quartz_job.job_class
     *
     * @mbg.generated
     */
    public void setJobClass(String jobClass) {
        this.jobClass = jobClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quartz_job.job_group
     *
     * @return the value of quartz_job.job_group
     *
     * @mbg.generated
     */
    public String getJobGroup() {
        return jobGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quartz_job.job_group
     *
     * @param jobGroup the value for quartz_job.job_group
     *
     * @mbg.generated
     */
    public void setJobGroup(String jobGroup) {
        this.jobGroup = jobGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quartz_job.status
     *
     * @return the value of quartz_job.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quartz_job.status
     *
     * @param status the value for quartz_job.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quartz_job.create_time
     *
     * @return the value of quartz_job.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quartz_job.create_time
     *
     * @param createTime the value for quartz_job.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quartz_job.create_by
     *
     * @return the value of quartz_job.create_by
     *
     * @mbg.generated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quartz_job.create_by
     *
     * @param createBy the value for quartz_job.create_by
     *
     * @mbg.generated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quartz_job.start_at
     *
     * @return the value of quartz_job.start_at
     *
     * @mbg.generated
     */
    public Date getStartAt() {
        return startAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quartz_job.start_at
     *
     * @param startAt the value for quartz_job.start_at
     *
     * @mbg.generated
     */
    public void setStartAt(Date startAt) {
        this.startAt = startAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quartz_job.end_at
     *
     * @return the value of quartz_job.end_at
     *
     * @mbg.generated
     */
    public Date getEndAt() {
        return endAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quartz_job.end_at
     *
     * @param endAt the value for quartz_job.end_at
     *
     * @mbg.generated
     */
    public void setEndAt(Date endAt) {
        this.endAt = endAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quartz_job.delete_time
     *
     * @return the value of quartz_job.delete_time
     *
     * @mbg.generated
     */
    public Date getDeleteTime() {
        return deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quartz_job.delete_time
     *
     * @param deleteTime the value for quartz_job.delete_time
     *
     * @mbg.generated
     */
    public void setDeleteTime(Date deleteTime) {
        this.deleteTime = deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quartz_job.delete_by
     *
     * @return the value of quartz_job.delete_by
     *
     * @mbg.generated
     */
    public String getDeleteBy() {
        return deleteBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quartz_job.delete_by
     *
     * @param deleteBy the value for quartz_job.delete_by
     *
     * @mbg.generated
     */
    public void setDeleteBy(String deleteBy) {
        this.deleteBy = deleteBy;
    }


    @Override
    public String toString() {
        return "QuartzJob{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", description='" + description + '\'' +
                ", cron='" + cron + '\'' +
                ", jobClass='" + jobClass + '\'' +
                ", jobGroup='" + jobGroup + '\'' +
                ", status='" + status + '\'' +
                ", createTime=" + createTime +
                ", createBy='" + createBy + '\'' +
                ", startAt=" + startAt +
                ", endAt=" + endAt +
                ", deleteTime=" + deleteTime +
                ", deleteBy='" + deleteBy + '\'' +
                '}';
    }
}