package com.microblog.points.dao.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table points
 */
public class Points {
    /**
     * Database Column Remarks:
     *   积分ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column points.points_id
     *
     * @mbg.generated
     */
    private Long pointsId;

    /**
     * Database Column Remarks:
     *   用户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column points.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     * Database Column Remarks:
     *   总积分
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column points.points
     *
     * @mbg.generated
     */
    private Long points;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column points.points_id
     *
     * @return the value of points.points_id
     *
     * @mbg.generated
     */
    public Long getPointsId() {
        return pointsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column points.points_id
     *
     * @param pointsId the value for points.points_id
     *
     * @mbg.generated
     */
    public void setPointsId(Long pointsId) {
        this.pointsId = pointsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column points.user_id
     *
     * @return the value of points.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column points.user_id
     *
     * @param userId the value for points.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column points.points
     *
     * @return the value of points.points
     *
     * @mbg.generated
     */
    public Long getPoints() {
        return points;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column points.points
     *
     * @param points the value for points.points
     *
     * @mbg.generated
     */
    public void setPoints(Long points) {
        this.points = points;
    }
}