package com.cloud.microblog.user.dao.model;

public class Location {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column location.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column location.mail
     *
     * @mbggenerated
     */
    private Long mail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column location.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column location.eaddress
     *
     * @mbggenerated
     */
    private String eaddress;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column location.id
     *
     * @return the value of location.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column location.id
     *
     * @param id the value for location.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column location.mail
     *
     * @return the value of location.mail
     *
     * @mbggenerated
     */
    public Long getMail() {
        return mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column location.mail
     *
     * @param mail the value for location.mail
     *
     * @mbggenerated
     */
    public void setMail(Long mail) {
        this.mail = mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column location.address
     *
     * @return the value of location.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column location.address
     *
     * @param address the value for location.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column location.eaddress
     *
     * @return the value of location.eaddress
     *
     * @mbggenerated
     */
    public String getEaddress() {
        return eaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column location.eaddress
     *
     * @param eaddress the value for location.eaddress
     *
     * @mbggenerated
     */
    public void setEaddress(String eaddress) {
        this.eaddress = eaddress;
    }
}