package com.cloud.microblog.blog.dao.mapper;

import com.cloud.microblog.blog.dao.model.Blog1;
import java.util.List;

public interface Blog1Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog1
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long blogId1);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog1
     *
     * @mbggenerated
     */
    int insert(Blog1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog1
     *
     * @mbggenerated
     */
    Blog1 selectByPrimaryKey(Long blogId1);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog1
     *
     * @mbggenerated
     */
    List<Blog1> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog1
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Blog1 record);
}