package com.cloud.microblog.blog.dao.mapper;

import com.cloud.microblog.blog.dao.model.BlogCollect;
import java.util.List;

public interface BlogCollectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_collect
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long collectId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_collect
     *
     * @mbggenerated
     */
    int insert(BlogCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_collect
     *
     * @mbggenerated
     */
    BlogCollect selectByPrimaryKey(Long collectId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_collect
     *
     * @mbggenerated
     */
    List<BlogCollect> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_collect
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BlogCollect record);
}