package com.microblog.authorization.dao.mapper;

import com.microblog.authorization.dao.model.ManagerUser;
import java.util.List;

public interface ManagerUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_user
     *
     * @mbggenerated
     */
    int insert(ManagerUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_user
     *
     * @mbggenerated
     */
    ManagerUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_user
     *
     * @mbggenerated
     */
    List<ManagerUser> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ManagerUser record);

    ManagerUser selectByUsername(String username);
    String selectSalt(String username);
}