package com.cloud.microblog.gateway.dao.model;

import java.util.Date;

public class BlogCollect {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_collect.collect_id
     *
     * @mbggenerated
     */
    private Long collectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_collect.blog_id
     *
     * @mbggenerated
     */
    private Long blogId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_collect.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_collect.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_collect.collect_id
     *
     * @return the value of blog_collect.collect_id
     *
     * @mbggenerated
     */
    public Long getCollectId() {
        return collectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_collect.collect_id
     *
     * @param collectId the value for blog_collect.collect_id
     *
     * @mbggenerated
     */
    public void setCollectId(Long collectId) {
        this.collectId = collectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_collect.blog_id
     *
     * @return the value of blog_collect.blog_id
     *
     * @mbggenerated
     */
    public Long getBlogId() {
        return blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_collect.blog_id
     *
     * @param blogId the value for blog_collect.blog_id
     *
     * @mbggenerated
     */
    public void setBlogId(Long blogId) {
        this.blogId = blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_collect.user_id
     *
     * @return the value of blog_collect.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_collect.user_id
     *
     * @param userId the value for blog_collect.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_collect.create_time
     *
     * @return the value of blog_collect.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_collect.create_time
     *
     * @param createTime the value for blog_collect.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}