package com.cloud.microblog.gateway.dao.model;

import java.util.Date;

public class BlogRepost {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_repost.repost_id
     *
     * @mbggenerated
     */
    private Long repostId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_repost.blog_id
     *
     * @mbggenerated
     */
    private Long blogId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_repost.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_repost.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_repost.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_repost.repost_id
     *
     * @return the value of blog_repost.repost_id
     *
     * @mbggenerated
     */
    public Long getRepostId() {
        return repostId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_repost.repost_id
     *
     * @param repostId the value for blog_repost.repost_id
     *
     * @mbggenerated
     */
    public void setRepostId(Long repostId) {
        this.repostId = repostId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_repost.blog_id
     *
     * @return the value of blog_repost.blog_id
     *
     * @mbggenerated
     */
    public Long getBlogId() {
        return blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_repost.blog_id
     *
     * @param blogId the value for blog_repost.blog_id
     *
     * @mbggenerated
     */
    public void setBlogId(Long blogId) {
        this.blogId = blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_repost.user_id
     *
     * @return the value of blog_repost.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_repost.user_id
     *
     * @param userId the value for blog_repost.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_repost.create_time
     *
     * @return the value of blog_repost.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_repost.create_time
     *
     * @param createTime the value for blog_repost.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_repost.content
     *
     * @return the value of blog_repost.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_repost.content
     *
     * @param content the value for blog_repost.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content;
    }
}