package com.clolud.microblog.search.entity;


import com.fasterxml.jackson.annotation.JsonProperty;

//@Document(indexName = "index_blog1", type = "blog1")
public class Blog1 {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog1.blog_id1
     *
     * @mbggenerated
     */
  //  @Id
    @JsonProperty("blog_id1")
    private Long blogId1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog1.user_id1
     *
     * @mbggenerated
     */
    @JsonProperty("user_id1")
    private Integer userId1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog1.content1
     *
     * @mbggenerated
     */
    private String content1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog1.text
     *
     * @mbggenerated
     */
    private String text;

    private Integer idd;


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog1.blog_id1
     *
     * @return the value of blog1.blog_id1
     *
     * @mbggenerated
     */
    public Long getBlogId1() {
        return blogId1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog1.blog_id1
     *
     * @param blogId1 the value for blog1.blog_id1
     *
     * @mbggenerated
     */
    public void setBlogId1(Long blogId1) {
        this.blogId1 = blogId1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog1.user_id1
     *
     * @return the value of blog1.user_id1
     *
     * @mbggenerated
     */
    public Integer getUserId1() {
        return userId1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog1.user_id1
     *
     * @param userId1 the value for blog1.user_id1
     *
     * @mbggenerated
     */
    public void setUserId1(Integer userId1) {
        this.userId1 = userId1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog1.content1
     *
     * @return the value of blog1.content1
     *
     * @mbggenerated
     */
    public String getContent1() {
        return content1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog1.content1
     *
     * @param content1 the value for blog1.content1
     *
     * @mbggenerated
     */
    public void setContent1(String content1) {
        this.content1 = content1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog1.text
     *
     * @return the value of blog1.text
     *
     * @mbggenerated
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog1.text
     *
     * @param text the value for blog1.text
     *
     * @mbggenerated
     */
    public void setText(String text) {
        this.text = text;
    }


    public Integer getIdd() {
        return idd;
    }

    public void setIdd(Integer idd) {
        this.idd = idd;
    }
}