package com.clolud.microblog.search.entity;

import lombok.Data;
import org.springframework.data.annotation.Id;
import org.springframework.data.elasticsearch.annotations.Document;

import java.util.Date;

//@ToString
@Data
@Document(indexName = "user", type = "demo")
public class UserDemo {


    public UserDemo(){

    }

    public UserDemo(Long userId, Long userNumber, String nickName, String loginPassword, String salt, String actualName, String gender, Byte age, String headerUrl, Byte status, String email, Byte emailActive, String phoneNum, Date registerTime, Date lastLoginTime, Date updateTime, Integer loginNums) {
        this.userId = userId;
        this.userNumber = userNumber;
        this.nickName = nickName;
        this.loginPassword = loginPassword;
        this.salt = salt;
        this.actualName = actualName;
        this.gender = gender;
        this.age = age;
        this.headerUrl = headerUrl;
        this.status = status;
        this.email = email;
        this.emailActive = emailActive;
        this.phoneNum = phoneNum;
        this.registerTime = registerTime;
        this.lastLoginTime = lastLoginTime;
        this.updateTime = updateTime;
        this.loginNums = loginNums;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_demo.user_id
     *
     * @mbggenerated
     */
    @Id
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_demo.user_number
     *
     * @mbggenerated
     */
    private Long userNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_demo.nick_name
     *
     * @mbggenerated
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_demo.login_password
     *
     * @mbggenerated
     */
    private String loginPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_demo.salt
     *
     * @mbggenerated
     */
    private String salt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_demo.actual_name
     *
     * @mbggenerated
     */
    private String actualName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_demo.gender
     *
     * @mbggenerated
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_demo.age
     *
     * @mbggenerated
     */
    private Byte age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_demo.header_url
     *
     * @mbggenerated
     */
    private String headerUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_demo.status
     *
     * @mbggenerated
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_demo.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_demo.email_active
     *
     * @mbggenerated
     */
    private Byte emailActive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_demo.phone_num
     *
     * @mbggenerated
     */
    private String phoneNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_demo.register_time
     *
     * @mbggenerated
     */
    private Date registerTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_demo.last_login_time
     *
     * @mbggenerated
     */
    private Date lastLoginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_demo.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_demo.login_nums
     *
     * @mbggenerated
     */
    private Integer loginNums;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_demo.user_id
     *
     * @return the value of user_demo.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_demo.user_id
     *
     * @param userId the value for user_demo.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_demo.user_number
     *
     * @return the value of user_demo.user_number
     *
     * @mbggenerated
     */
    public Long getUserNumber() {
        return userNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_demo.user_number
     *
     * @param userNumber the value for user_demo.user_number
     *
     * @mbggenerated
     */
    public void setUserNumber(Long userNumber) {
        this.userNumber = userNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_demo.nick_name
     *
     * @return the value of user_demo.nick_name
     *
     * @mbggenerated
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_demo.nick_name
     *
     * @param nickName the value for user_demo.nick_name
     *
     * @mbggenerated
     */
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_demo.login_password
     *
     * @return the value of user_demo.login_password
     *
     * @mbggenerated
     */
    public String getLoginPassword() {
        return loginPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_demo.login_password
     *
     * @param loginPassword the value for user_demo.login_password
     *
     * @mbggenerated
     */
    public void setLoginPassword(String loginPassword) {
        this.loginPassword = loginPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_demo.salt
     *
     * @return the value of user_demo.salt
     *
     * @mbggenerated
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_demo.salt
     *
     * @param salt the value for user_demo.salt
     *
     * @mbggenerated
     */
    public void setSalt(String salt) {
        this.salt = salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_demo.actual_name
     *
     * @return the value of user_demo.actual_name
     *
     * @mbggenerated
     */
    public String getActualName() {
        return actualName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_demo.actual_name
     *
     * @param actualName the value for user_demo.actual_name
     *
     * @mbggenerated
     */
    public void setActualName(String actualName) {
        this.actualName = actualName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_demo.gender
     *
     * @return the value of user_demo.gender
     *
     * @mbggenerated
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_demo.gender
     *
     * @param gender the value for user_demo.gender
     *
     * @mbggenerated
     */
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_demo.age
     *
     * @return the value of user_demo.age
     *
     * @mbggenerated
     */
    public Byte getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_demo.age
     *
     * @param age the value for user_demo.age
     *
     * @mbggenerated
     */
    public void setAge(Byte age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_demo.header_url
     *
     * @return the value of user_demo.header_url
     *
     * @mbggenerated
     */
    public String getHeaderUrl() {
        return headerUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_demo.header_url
     *
     * @param headerUrl the value for user_demo.header_url
     *
     * @mbggenerated
     */
    public void setHeaderUrl(String headerUrl) {
        this.headerUrl = headerUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_demo.status
     *
     * @return the value of user_demo.status
     *
     * @mbggenerated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_demo.status
     *
     * @param status the value for user_demo.status
     *
     * @mbggenerated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_demo.email
     *
     * @return the value of user_demo.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_demo.email
     *
     * @param email the value for user_demo.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_demo.email_active
     *
     * @return the value of user_demo.email_active
     *
     * @mbggenerated
     */
    public Byte getEmailActive() {
        return emailActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_demo.email_active
     *
     * @param emailActive the value for user_demo.email_active
     *
     * @mbggenerated
     */
    public void setEmailActive(Byte emailActive) {
        this.emailActive = emailActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_demo.phone_num
     *
     * @return the value of user_demo.phone_num
     *
     * @mbggenerated
     */
    public String getPhoneNum() {
        return phoneNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_demo.phone_num
     *
     * @param phoneNum the value for user_demo.phone_num
     *
     * @mbggenerated
     */
    public void setPhoneNum(String phoneNum) {
        this.phoneNum = phoneNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_demo.register_time
     *
     * @return the value of user_demo.register_time
     *
     * @mbggenerated
     */
    public Date getRegisterTime() {
        return registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_demo.register_time
     *
     * @param registerTime the value for user_demo.register_time
     *
     * @mbggenerated
     */
    public void setRegisterTime(Date registerTime) {
        this.registerTime = registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_demo.last_login_time
     *
     * @return the value of user_demo.last_login_time
     *
     * @mbggenerated
     */
    public Date getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_demo.last_login_time
     *
     * @param lastLoginTime the value for user_demo.last_login_time
     *
     * @mbggenerated
     */
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_demo.update_time
     *
     * @return the value of user_demo.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_demo.update_time
     *
     * @param updateTime the value for user_demo.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_demo.login_nums
     *
     * @return the value of user_demo.login_nums
     *
     * @mbggenerated
     */
    public Integer getLoginNums() {
        return loginNums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_demo.login_nums
     *
     * @param loginNums the value for user_demo.login_nums
     *
     * @mbggenerated
     */
    public void setLoginNums(Integer loginNums) {
        this.loginNums = loginNums;
    }
}