package com.microblog.user.dao.mapper;

import com.microblog.user.dao.model.Concerns;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ConcernsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table concerns
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table concerns
     *
     * @mbg.generated
     */
    int insert(Concerns record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table concerns
     *
     * @mbg.generated
     */
    Concerns selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table concerns
     *
     * @mbg.generated
     */
    List<Concerns> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table concerns
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Concerns record);

    int delete(@Param("userId") long userId,@Param("userId") long concernId);

}