package com.microblog.user.dao.mapper;

import com.microblog.user.dao.model.Fans;
import java.util.List;

public interface FansMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fans
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long fansId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fans
     *
     * @mbg.generated
     */
    int insert(Fans record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fans
     *
     * @mbg.generated
     */
    Fans selectByPrimaryKey(Long fansId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fans
     *
     * @mbg.generated
     */
    List<Fans> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fans
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Fans record);
}