package com.microblog.user.dao.mapper;

import com.microblog.user.dao.model.Relation;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface RelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation
     *
     * @mbg.generated
     */
    int insert(Relation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation
     *
     * @mbg.generated
     */
    Relation selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation
     *
     * @mbg.generated
     */
    List<Relation> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Relation record);

    /***
     * 取消关注
     * @param userId
     * @param folleeId
     * @return
     */
    int unfollow(@Param("follerId") long userId,@Param("folleeId") long folleeId);

    List<Long> selectAllByFollowerId(@Param("follerId") long follerId);

    List<Long> selectAllByFolloweeId(@Param("folleeId") long folleeId);

}