package com.microblog.user.dao.mapper;

import com.microblog.user.dao.model.UserDelete;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UserDeleteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_delete
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_delete
     *
     * @mbg.generated
     */
    int insert(UserDelete record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_delete
     *
     * @mbg.generated
     */
    UserDelete selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_delete
     *
     * @mbg.generated
     */
    List<UserDelete> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_delete
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserDelete record);

    int deleteByUid(@Param("uids") List<Long> uids);
}