package com.cloud.microblog.user.dao.mapper;

import com.cloud.microblog.user.dao.model.UserDemo;
import java.util.List;

public interface UserDemoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_demo
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_demo
     *
     * @mbggenerated
     */
    int insert(UserDemo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_demo
     *
     * @mbggenerated
     */
    UserDemo selectByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_demo
     *
     * @mbggenerated
     */
    List<UserDemo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_demo
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserDemo record);
}