package com.microblog.user.dao.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table concerns
 */
public class Concerns {
    /**
     * Database Column Remarks:
     *   关注ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column concerns.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   用户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column concerns.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     * Database Column Remarks:
     *   关注ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column concerns.concern_id
     *
     * @mbg.generated
     */
    private Long concernId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column concerns.id
     *
     * @return the value of concerns.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column concerns.id
     *
     * @param id the value for concerns.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column concerns.user_id
     *
     * @return the value of concerns.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column concerns.user_id
     *
     * @param userId the value for concerns.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column concerns.concern_id
     *
     * @return the value of concerns.concern_id
     *
     * @mbg.generated
     */
    public Long getConcernId() {
        return concernId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column concerns.concern_id
     *
     * @param concernId the value for concerns.concern_id
     *
     * @mbg.generated
     */
    public void setConcernId(Long concernId) {
        this.concernId = concernId;
    }
}