package com.microblog.user.dao.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table fans
 */
public class Fans {
    /**
     * Database Column Remarks:
     *   粉丝ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fans.fans_id
     *
     * @mbg.generated
     */
    private Long fansId;

    /**
     * Database Column Remarks:
     *   用户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fans.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fans.fans_id
     *
     * @return the value of fans.fans_id
     *
     * @mbg.generated
     */
    public Long getFansId() {
        return fansId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fans.fans_id
     *
     * @param fansId the value for fans.fans_id
     *
     * @mbg.generated
     */
    public void setFansId(Long fansId) {
        this.fansId = fansId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fans.user_id
     *
     * @return the value of fans.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fans.user_id
     *
     * @param userId the value for fans.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }
}