package com.microblog.user.dao.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table relation
 */
public class Relation {
    /**
     * Database Column Remarks:
     *   ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relation.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   关注者ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relation.followerId
     *
     * @mbg.generated
     */
    private Long followerid;

    /**
     * Database Column Remarks:
     *   被关注者ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relation.followeeId
     *
     * @mbg.generated
     */
    private Long followeeid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relation.id
     *
     * @return the value of relation.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relation.id
     *
     * @param id the value for relation.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relation.followerId
     *
     * @return the value of relation.followerId
     *
     * @mbg.generated
     */
    public Long getFollowerid() {
        return followerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relation.followerId
     *
     * @param followerid the value for relation.followerId
     *
     * @mbg.generated
     */
    public void setFollowerid(Long followerid) {
        this.followerid = followerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relation.followeeId
     *
     * @return the value of relation.followeeId
     *
     * @mbg.generated
     */
    public Long getFolloweeid() {
        return followeeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relation.followeeId
     *
     * @param followeeid the value for relation.followeeId
     *
     * @mbg.generated
     */
    public void setFolloweeid(Long followeeid) {
        this.followeeid = followeeid;
    }
}