package com.microblog.user.dao.model;

import lombok.ToString;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table user_delete
 */
@ToString
public class UserDelete {
    /**
     * Database Column Remarks:
     *   删除用户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_delete.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   用户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_delete.u_id
     *
     * @mbg.generated
     */
    private Long uId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_delete.id
     *
     * @return the value of user_delete.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_delete.id
     *
     * @param id the value for user_delete.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_delete.u_id
     *
     * @return the value of user_delete.u_id
     *
     * @mbg.generated
     */
    public Long getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_delete.u_id
     *
     * @param uId the value for user_delete.u_id
     *
     * @mbg.generated
     */
    public void setuId(Long uId) {
        this.uId = uId;
    }
}