package com.microblog.shorturl.dao.mapper;

import com.microblog.shorturl.dao.model.Url;
import java.util.List;

public interface UrlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table url
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table url
     *
     * @mbg.generated
     */
    int insert(Url record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table url
     *
     * @mbg.generated
     */
    Url selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table url
     *
     * @mbg.generated
     */
    List<Url> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table url
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Url record);

    Url selectByUrl(String url);

}