package com.microblog.blog.dao.mapper;

import com.microblog.blog.dao.model.CommentLike;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CommentLikeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_like
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long likeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_like
     *
     * @mbggenerated
     */
    int insert(CommentLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_like
     *
     * @mbggenerated
     */
    CommentLike selectByPrimaryKey(Long likeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_like
     *
     * @mbggenerated
     */
    List<CommentLike> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_like
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CommentLike record);


    Long selectCountByCommentId(@Param("commentId") Long commentId);
    Long selectCount(@Param("commentId") Long blogId,@Param("userId") Long  userId);
    Long delete(@Param("commentId") Long blogId,@Param("userId") Long  userId);


}