package com.microblog.shorturl.dao.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table url
 */
public class Url {
    /**
     * Database Column Remarks:
     *   url id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column url.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   URL
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column url.url
     *
     * @mbg.generated
     */
    private String url;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column url.id
     *
     * @return the value of url.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column url.id
     *
     * @param id the value for url.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column url.url
     *
     * @return the value of url.url
     *
     * @mbg.generated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column url.url
     *
     * @param url the value for url.url
     *
     * @mbg.generated
     */
    public void setUrl(String url) {
        this.url = url;
    }
}